org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
risingStonesVersion=0.1.0-SNAPSHOT
risingStonesProjectUrl=https://github.com/LimitAL/risingstones-community-android
risingStonesLicenseName=MIT
risingStonesLicenseUrl=https://opensource.org/license/mit
risingStonesScmConnection=scm:git:https://github.com/LimitAL/risingstones-community-android.git
risingStonesScmDeveloperConnection=scm:git:ssh://git@github.com/LimitAL/risingstones-community-android.git
risingStonesScmUrl=https://github.com/LimitAL/risingstones-community-android
